/**
 * scripts/dev/gen-theme.ts — generate apps/mobile/lib/theme-tokens.ts from global.css.
 *
 * NativeWind reads the CSS variables in apps/mobile/global.css, but navigation
 * chrome, the tab bar, bottom sheets, and charts need the same colors as plain
 * JS strings. Those used to be a hand-maintained second copy in lib/theme.ts,
 * which meant a Moonchild token sync (documented as "global.css + ui/" in
 * AGENTS.md) silently left the JS copy on the old palette — and contrast-check
 * reads only global.css, so `npm run check` still passed.
 *
 * global.css is now the single source. This regenerates the JS copy from it.
 *
 * Usage:
 *   npm run gen-theme            # rewrite lib/theme-tokens.ts
 *   npm run gen-theme -- --check # fail if the file is stale (used by npm run check)
 */
import fs from 'node:fs';
import path from 'node:path';

const ROOT = path.resolve(__dirname, '../..');
const CSS_PATH = path.join(ROOT, 'apps/mobile/global.css');
const OUT_PATH = path.join(ROOT, 'apps/mobile/lib/theme-tokens.ts');

const BLOCKS = [
  { selector: ':root', key: 'light' },
  { selector: '.dark:root', key: 'dark' },
] as const;

/** An HSL triple as authored in the CSS, e.g. `0 0% 9%`. */
const HSL_TRIPLE = /^[\d.]+\s+[\d.]+%\s+[\d.]+%$/;

/** `--card-foreground` -> `cardForeground`, `--chart-1` -> `chart1`. */
function toCamelCase(cssName: string): string {
  return cssName.replace(/-([a-z0-9])/g, (_, c: string) => c.toUpperCase());
}

function stripComments(css: string): string {
  return css.replace(/\/\*[\s\S]*?\*\//g, '');
}

/** Parsed declarations in authoring order, so the generated file mirrors the CSS. */
function parseBlock(css: string, selector: string): [name: string, value: string][] {
  const re = new RegExp(`${selector.replace(/[.:]/g, '\\$&')}\\s*\\{([^}]*)\\}`);
  const match = re.exec(stripComments(css));
  if (!match) throw new Error(`Missing ${selector} block in ${CSS_PATH}`);

  const declarations: [string, string][] = [];
  for (const line of match[1].split(';')) {
    const m = /--([a-z0-9-]+)\s*:\s*(.+)/.exec(line);
    if (!m) continue;
    declarations.push([m[1], m[2].trim()]);
  }
  if (declarations.length === 0) throw new Error(`No custom properties in ${selector}`);
  return declarations;
}

/**
 * Colors become `hsl(...)` strings for React Native props; anything else (radius)
 * passes through as authored.
 */
function toJsValue(raw: string): string {
  return HSL_TRIPLE.test(raw) ? `hsl(${raw})` : raw;
}

function render(css: string): string {
  const lightDeclarations = parseBlock(css, BLOCKS[0].selector);
  const darkDeclarations = parseBlock(css, BLOCKS[1].selector);

  const lightNames = lightDeclarations.map(([name]) => name);
  const darkValues = new Map(darkDeclarations);

  // `.dark:root` legitimately overrides only a subset (--radius, for example, is
  // theme-independent), but a token it declares without a `:root` counterpart has
  // no light-mode value at all.
  const orphaned = [...darkValues.keys()].filter((name) => !lightNames.includes(name));
  if (orphaned.length > 0) {
    throw new Error(
      `${BLOCKS[1].selector} declares token(s) missing from ${BLOCKS[0].selector} in global.css: ` +
        `${orphaned.join(', ')}`
    );
  }

  const typeBody = lightNames.map((name) => `  ${toCamelCase(name)}: string;`).join('\n');

  // Dark inherits any token it doesn't override, mirroring the CSS cascade.
  const themeBody = [
    { key: 'light', resolve: (name: string, light: string) => light },
    { key: 'dark', resolve: (name: string, light: string) => darkValues.get(name) ?? light },
  ]
    .map(({ key, resolve }) => {
      const entries = lightDeclarations
        .map(([name, light]) => `    ${toCamelCase(name)}: '${toJsValue(resolve(name, light))}',`)
        .join('\n');
      return `  ${key}: {\n${entries}\n  },`;
    })
    .join('\n');

  return `/**
 * GENERATED by scripts/dev/gen-theme.ts — do not edit by hand.
 *
 * Source of truth: apps/mobile/global.css. Change the tokens there, then run
 * \`npm run gen-theme\`. \`npm run check\` fails if this file is stale.
 */

export type ThemeTokens = {
${typeBody}
};

export const THEME: Record<'light' | 'dark', ThemeTokens> = {
${themeBody}
};
`;
}

function main(): void {
  const checkOnly = process.argv.includes('--check');
  const next = render(fs.readFileSync(CSS_PATH, 'utf8'));
  const current = fs.existsSync(OUT_PATH) ? fs.readFileSync(OUT_PATH, 'utf8') : null;

  if (current === next) {
    console.log('gen-theme: lib/theme-tokens.ts is up to date with global.css');
    return;
  }

  if (checkOnly) {
    console.error(
      'gen-theme: FAILED — apps/mobile/lib/theme-tokens.ts is out of date with\n' +
        'apps/mobile/global.css. Run `npm run gen-theme` and commit the result.\n\n' +
        'This usually means design tokens were synced into global.css without\n' +
        'regenerating the JS copy that the tab bar, navigation chrome, bottom\n' +
        'sheets, and charts read.'
    );
    process.exit(1);
  }

  fs.writeFileSync(OUT_PATH, next);
  console.log(`gen-theme: wrote ${path.relative(ROOT, OUT_PATH)} from global.css`);
}

main();
